services:
  - type: web
    name: nextjs-ssr-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    branch: main
    autoDeploy: true
    pullRequestPreviewsEnabled: true
